[project]
name = "meilisearch-mistral"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.0.0",
    "meilisearch>=0.40.0",
    "mistralai>=1.12.2",
    "python-dotenv>=1.2.1",
    "tqdm>=4.67.3",
]
